### ISSUE TITLE
Generates invalid C-code

### ISSUE THREAD

**Issue by gvanem** [rrozansk/Scanner-Parser-Generator#1]
This project looks like what I need. But trying to generate some C-code with:
```
c:\Python\SPag\examples\JSON> spag_cli -f -s scanner.json -p parser.json -g c
``` 

and trying to compile `out_JSON_JSON.c` causes lots of errors. Like:
```raw
Microsoft (R) C/C++ Optimizing Compiler Version 19.28.29333 for x86
out_JSON_JSON.c
.\out_JSON_JSON.h(31): error C2059: syntax error: '('
.\out_JSON_JSON.h(40): error C2146: syntax error: missing ')' before identifier 'type'
.\out_JSON_JSON.h(40): error C2061: syntax error: identifier 'type'
.\out_JSON_JSON.h(40): error C2059: syntax error: ';'
.\out_JSON_JSON.h(40): error C2059: syntax error: ','
.\out_JSON_JSON.h(46): error C2059: syntax error: ')'
.\out_JSON_JSON.h(52): error C2061: syntax error: identifier 'type'
.\out_JSON_JSON.h(52): error C2059: syntax error: ';'
.\out_JSON_JSON.h(52): error C2059: syntax error: '<parameter-list>'
out_JSON_JSON.c(23): error C2061: syntax error: identifier 'JSON_token_type_t'
```
I tried to modify `c.py`, but there are several places where reserved words like `NULL` should be turned into `_NULL`.

**Comment by rrozansk** [comment]
Hello @gvanem, it looks like you are trying to use the parser generation flag (-p) which is not yet supported as described in the README. See here: https://github.com/rrozansk/SPaG#status. As for '_NULL', it is a special definition that may not be present in all compilers. Finally, if you need a compiler generator to build the scanner/parser, may i suggest something like 'Flex/Lex' or 'Yacc/Bison' as an alternative to SPaG as these are more reliable battle tested programs which may offer much more extensive features, help, and support.

**Comment by gvanem** [comment]
> As for '_NULL', it is a special definition that may not be present in all compilers.

Can you name one compiler that does not have `NULL`? You add a `#include <stdio.h>` and `NULL` is almost always defined to `0`.

> may i suggest something like 'Flex/Lex' or 'Yacc/Bison' 

I know these tools. But (except for the awful `.json` files) it seemed your tool looked more compact.

**Comment by rrozansk** [comment]
Hey @gvanem, I cannot name any C compilers without NULL, but that is not what I am stating. Rather, that '_NULL' is not necessarily the same as 'NULL'. The former is an implementation detail and not portable. The latter is what should be used as it is what is actually defined in the stdio.h header file as you described.

As for the JSON files, I concur that they could be in a better format. This way was chosen for simplicity as it makes parsing the input easier as python natively support JSON.

Lastly, I would like to say that this project has mostly gone stale since I have not had any time to work on it in quite a while. If you are up to the task and the compactness of the tool appeals to you then you can certainly feel free to contribute and it would be very much appreciated!

**Comment by gvanem** [comment]
>  Rather, that '_NULL' is not necessarily the same as 'NULL'. 

Yes, off-course not. I meant that one cannot use `NULL` in an enum-list like you did.
Hence `_NULL` (or `JSON_NULL` in this case) should be used.
Closing this now.
